name = "tsa-content"
type = "webpack"
route = ''
zone_id = ''
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
site = {bucket = "./public",entry-point = "workers-site"}
compatibility_date = "2023-07-12"
